# 2026-05-29-16:35
experiment:
  method_name: demo
  json_path: data/dataset_json/beat_clip/test.json
  data_path: data/dataset/beat_clip
  output_dir: data/result
  content_type: image
  prompt_type: basic
  batch_save_size: 100
  max_errors: 100
  debug_mode: true
  debug_limit: 100
  seed: 42
model_config:
  model_name: Qwen/Qwen2.5-VL-3B-Instruct
  load_lora: true
  lora_path: models/demo/Qwen2.5-VL-3B-Instruct/checkpoint-14740
gen_params:
  max_new_tokens: 2048
  do_sample: false
prompts:
  basic: '# Role

    あなたは世界レベルのストリートダンス・コンテンポラリーダンスの専門審査員です。

    # Task

    この画像のダンスのジャンルと、動きの名前を教えてください。'
