[project]
name = "make-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datetime>=5.5",
    "librosa>=0.11.0",
    "madmom",
    "matplotlib>=3.10.5",
    "moviepy>=2.2.1",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.2",
    "paramiko>=4.0.0",
    "pillow>=11.3.0",
    "pyfftw>=0.15.0",
    "setuptools>=80.9.0",
    "tqdm>=4.67.1",
]


[tool.uv.sources]
madmom = { git = "https://github.com/CPJKU/madmom.git" }

